allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - json-editor-vue
  - sharp
  - unrs-resolver
  - vue-demi
